name = "spirit-tracker-api"
main = "src/index.ts"
compatibility_date = "2026-02-15"
workers_dev = true
minify = true

[vars]
JWT_ISS = "spirit-tracker-api"
JWT_AUD = "spirit-tracker-api"
ALLOWED_ORIGIN = "https://spirit.codexwilkes.com"
GOOGLE_CLIENT_ID = "476657631811-3qmp79ul2bb37r1g6p8jaq5g3jjikk3j.apps.googleusercontent.com"
GITHUB_CLIENT_ID = "Ov23libK463TurCqoPz1"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "__KV_ID__"
